#!/bin/bash

#file=v5/resTh
#rm -f $file/*
#
#echo $file
#for i in 1 4 8 12 16 20 24 28 32 40 
#do 
#	OMP_NUM_THREADS=${i} mandelbrot > $file/cpumanout-$i 
#	OMP_NUM_THREADS=${i} mandelbrot >>$file/cpumanout-$i
#	echo $i >> $file/timeRes
#	echo $i >> $file/timeRes
#	echo "$i Thread RUN"
#done
#
#for i in 1 4 8 12 16 20 24 28 32 40
#do 
#	cat $file/cpumanout-$i | grep "Scalar kernel runtime" | awk '{print $4}' >> $file/scalar
#	cat $file/cpumanout-$i | grep "Scalar complex kernel" | awk '{print $4}' >> $file/complex
#	cat $file/cpumanout-$i | grep "SIMD complex kernel" | awk '{print $4}' >>   $file/Scomplex
#	cat $file/cpumanout-$i | grep "SIMD kernel" | awk '{print $4}' >>           $file/Skernel
#	cat $file/cpumanout-$i | grep "Intrinsic kernel" | awk '{print $4}' >>      $file/intrin
#	cat $file/cpumanout-$i | grep "Complex/complex" | awk '{print $3}' >>       $file/CCspeed
#	cat $file/cpumanout-$i | grep "Speed-up SIMD" | awk '{print $3}' >>         $file/Sspeed
#	cat $file/cpumanout-$i | grep "Speed-up intrinsic" | awk '{print $3}' >>    $file/Ispeed
#done

#cd $file
#paste timeRes scalar complex Skernel Scomplex intrin > timeResultsCPU
#paste timeRes CCspeed Sspeed Ispeed > speedupsCPU
name=gatherbound_calu
file=${name}_dir/resTh
rm -f $file/*
###########  MEMORYFOOTPRINT

#for i in  4 16 64 128 256 512 1024 2048 4096
#do 
#t=$(( i*15360 ))
#	OMP_NUM_THREADS=20 $name $t  > $file/cpumanout-$i 
#	OMP_NUM_THREADS=20 $name $t  >>$file/cpumanout-$i
#	echo $t
#done

for i in 1 4 8 12 16 20 24 40 
do 
	OMP_NUM_THREADS=${i} $name > $file/cpumanout-$i 
	OMP_NUM_THREADS=${i} $name >>$file/cpumanout-$i
	echo $i >> $file/timeRes
	echo $i >> $file/timeRes
	echo "$i Thread RUN"
done

#for i in 4 16 64 128 256 512 1024 2048 4096
for i in 1 4 8 12 16 20 24 40 
do 
	cat $file/cpumanout-$i | grep "Scalar runtime \[ms\]:" | awk '{print $4}' >> $file/scalar
	cat $file/cpumanout-$i | grep "^Easy runtime \[ms\]" | awk '{print $4}' >> $file/easy
	cat $file/cpumanout-$i | grep "SIMD runtime \[ms\]:" | awk '{print $4}' >> $file/simd
	cat $file/cpumanout-$i | grep "Intrinsic runtime \[ms\]:" | awk '{print $4}' >> $file/Intrin
	cat $file/cpumanout-$i | grep "Speed-up SIMD" | awk '{print $3}' >> $file/speedCpu
	cat $file/cpumanout-$i | grep "Speed-up intrinsic:" | awk '{print $3}' >> $file/speedintrin
	cat $file/cpumanout-$i | grep "Speed-up Easy"       | awk '{print $3}' >> $file/speedeasy
#	cat $file/cpumanout-$i | grep "Mem size =" | awk '{print $4}' >> $file/memRes
	echo $i >> $file/memRes
	echo $i >> $file/memRes
	#cat $file/cpumano:ut-$i | grep "Mem size =" | awk '{print $4}' >> $file/memRes
done
cd $file
paste memRes scalar easy simd Intrin > ResultsCPU
paste memRes speedeasy speedCpu speedintrin > speedupsCPU
